apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - https://github.com/stefanprodan/podinfo/deploy/bases/frontend?ref=6.0.0
  - https://github.com/stefanprodan/podinfo/deploy/bases/backend?ref=6.0.0
  - https://github.com/stefanprodan/podinfo/deploy/bases/cache?ref=6.0.0
  - namespace.yaml
images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.0.0
  - name: redis
    newName: public.ecr.aws/docker/library/redis
    newTag: 6.2.0